name: Publish Kobweb IntelliJ Plugin

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Add secret Gradle properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.KOBWEB_IJ_PLUGIN_GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Publish Kobweb IntelliJ Plugin
        run: ./gradlew :plugin:publishPlugin
