name: Verify Kobweb IntelliJ Plugin Compatibility

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify Kobweb IntelliJ Plugin
        run: ./gradlew :plugin:verifyPlugin
